export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20 md:py-28">
      <h1 className="text-3xl md:text-4xl font-semibold tracking-tight mb-8">Terms of Service</h1>
      <div className="prose prose-sm text-muted leading-relaxed space-y-6">
        <p className="text-sm">Last updated: January 1, 2026</p>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">1. Acceptance of Terms</h2>
          <p className="text-sm">
            By accessing or using Onton's services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">2. Use of Services</h2>
          <p className="text-sm">
            Our services are designed to help you create AI-generated interior designs and discover products for your home. You agree to use our services only for lawful purposes and in accordance with these terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">3. Account Registration</h2>
          <p className="text-sm">
            To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">4. Intellectual Property</h2>
          <p className="text-sm">
            AI-generated designs created through our platform are subject to our intellectual property policies. You retain rights to images you upload. Content generated by our AI tools may be used for personal and commercial purposes according to your subscription plan.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">5. Subscriptions and Billing</h2>
          <p className="text-sm">
            Paid subscriptions are billed on a recurring basis. You may cancel your subscription at any time. Refunds are handled according to our refund policy.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">6. Limitation of Liability</h2>
          <p className="text-sm">
            Onton provides its services "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from the use of our services.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mt-8 mb-3">7. Contact</h2>
          <p className="text-sm">
            For questions regarding these Terms of Service, please contact us at legal@onton.com.
          </p>
        </section>
      </div>
    </div>
  )
}
